### ISSUE TITLE
vue 单元测试入门

### ISSUE THREAD

**Issue by zwmmm** [zwmmm/blog#12]
### 工具库
[Vue Test Utils](https://vue-test-utils.vuejs.org/zh/)

#### [Jest](https://jestjs.io/zh-Hans/)
Facebook 出品的测试运行器，针对vue有`vue-jest`来测试vue的单文件组件。但是`vue-jest`并不支持`vue-loader`的所有功能。

优点：
- 只需少量配置，就可以测试vue
- 自带断言库

缺点：
- 不支持[自定义块](https://vue-loader.vuejs.org/zh/guide/custom-blocks.html#example)
- 不够灵活

#### [Mocha](https://github.com/mochajs/mocha)
优点：
- 对vue支持很好，功能更加全面
- 配置更加的灵活

缺点：
- 配置繁琐，需要配合webpack使用
- 需要自己搭配断言库

## 环境搭建
在这个项目中，我采用 Jest 和 @vue/test-utils 进行单元测试

1.下载npm包
```bash
tnpm i -D jest @vue/test-utils vue-jest babel-jest
```

2.编写配置文件
```json
# package.json

{
    "jest": {
        "testURL": "http://localhost",
        "moduleFileExtensions": [
            "js",
            "vue"
        ],
        "transform": {
            "^.+\\.js$": "<rootDir>/node_modules/babel-jest",
            ".*\\.(vue)$": "vue-jest"
        },
        "moduleNameMapper": {
            "^@/(.*)$": "<rootDir>/src/$1"
        },
    }
}
```

3.编写测试用例
先在根目录下创建`__test__`文件夹，然后在文件夹下创建以`.test.js`的文件

4.启动测试
先在 package.json 的script中添加`"test": "jest"`，根目录下运行命令`npm run test`

##### `test(name, fn, timeout)`
> 别名 it(name, fn, timeout)
执行一个测试，name表示测试名称，fn为测试函数，timeout是延迟执行的时间。

##### `expect(value)`
用来获取期望值

##### `toBe()`
精准匹配器

使用上面三个api就可以编写一个最简单的测试用例
```js
it('2+2等于4', () => {
  expect(2 + 2).toBe(4);
});
```

##### 更多的匹配器
- toEqual 递归检查对象或数组的每个字段。
```js
it('测试对象', () => {
  const data = {one: 1};
  data['two'] = 2;
  expect(data).toEqual({one: 1, two: 2});
});
```

- toBeNull 只匹配 null
- toBeUndefined 只匹配 undefined
- toBeDefined 与 toBeUndefined 相反
- toBeTruthy 匹配任何 if 语句为真
- toBeFalsy 匹配任何 if 语句为假
```js
it('null', () => {
  const n = null;
  expect(n).toBeNull();
  expect(n).toBeDefined();
  expect(n).toBeUndefined();
  expect(n).toBeTruthy();
  expect(n).toBeFalsy();
});
```

- toBeCloseTo 匹配浮点数
```js
it('两个浮点数字相加', () => {
  const value = 0.1 + 0.2;
  expect(value).toBe(0.3);        //这句会报错，因为浮点数有舍入误差
  expect(value).toBeCloseTo(0.3); // 这句可以运行
});
```

- toMatch 用正则匹配字符串
```js
it('匹配字符串', () => {
  expect('Christoph').toMatch(/stop/);
});
```

- toContain 匹配期望值中是否包含该子项
```js
const shoppingList = [
  'diapers',
  'kleenex',
  'trash bags',
  'paper towels',
  'beer',
];

it('购物清单（shopping list）里面有啤酒（beer）', () => {
  expect(shoppingList).toContain('beer');
});
```

- not 可以用在所有的匹配器前面, 表示反义
```js
it('null', () => {
  expect(null).not.toBeNull();
});
```
> 更多的匹配器参考文档 https://jestjs.io/docs/zh-Hans/expect

##### `describe(name, fn)` 用来包裹一组测试
```js
const myBeverage = {
  delicious: true,
  sour: false,
};

describe('my beverage', () => {
  it('is delicious', () => {
    expect(myBeverage.delicious).toBeTruthy();
  });

  it('is not sour', () => {
    expect(myBeverage.sour).toBeFalsy();
  });
});
```

#### Wrapper 包裹器
> 简单的理解下,其实就是将vue组件包裹一层,使其拥有一些测试api

创建Wrapper
- mount(component, options)
- shallowMount(component, options) 不包含子组件

component 代表vue组件
options   代表初始化的数据

options包含如下
```js
{
  data: {},
  propsData: {},
  slots: {
    default: [Bar, FooBar],
    fooBar: FooBar,
  },
  // 模拟全局属性
  mocks: {
    $route
  },
  methods: {},
}
```

#### Wrapper上的属性

- vm vue的实例,相当于组件中的this
- element 组件的根元素, 相当于$el
- options 组件的配置项

#### Wrapper上的方法

- setData 设置data
- setMethods 设置方法
- setProps 设置props
- attributes 获取属性
- classes 获取class
- contains 判断 Wrapper 是否包含了一个匹配选择器的元素或组件。
- exists 判断 Wrapper 是否存在
- find 返回匹配的组件或者dom,并且包装成Wrapper返回
- findAll 同上, 返回所有匹配的
- html 返回html
- is 判断是不是匹配的dom或者组件
- isEmpty 判断有没有子节点
- isVisible 判断是否可见, 其实就是判断v-show
- props 获取props
- setChecked 设置 checkbox 或者 radio 的 v-model
- setSelected 设置 option 
- setValue 设置 v-model
- text 返回 Wrapper 的文本内容
- trigger 触发一个事件

## demo
- [官方案例](https://github.com/vuejs/vue-test-utils-getting-started)

## 参考文档
> 看文档才是重点

- [Vue Test Utils](https://vue-test-utils.vuejs.org/zh/)
- [选择器的规则](https://vue-test-utils.vuejs.org/zh/api/selectors.html)
- [Vue 组件单元测试](https://cn.vuejs.org/v2/cookbook/unit-testing-vue-components.html)
- [Jest 官方文档](https://jestjs.io/zh-Hans/)

**Comment by wanxianping** [comment]
牛逼呀

**Comment by zwmmm** [comment]
> 牛逼呀

🔢
